version: 2.1
jobs:
  commits:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - run:
          name: set up git
          command: |
            git config --global user.email "$USEREMAIL"
            git config --global user.name "$USERNAME"
      - run: 
          name: Make Commits
          command: | 
            git checkout -b "$CIRCLE_BUILD_NUM"
            git commit --allow-empty -m "$CIRCLE_SHA1"
            git push --set-upstream origin "$CIRCLE_BUILD_NUM"
            git checkout master
            git merge "$CIRCLE_BUILD_NUM" --no-edit
            git push
            REMOTE="origin" && MASTER="master"
            git branch -r |  grep "^  ${REMOTE}/" | sed "s|^  ${REMOTE}/|:|" | grep -v "^:HEAD" | grep -v "^:${MASTER}$" | xargs git push ${REMOTE}

workflows:
  version: 2.1
  Scheduled Commits:
    triggers:
      - schedule:
          cron: '20,30,40,50 1,3,9,15,18 * * *'
          filters:
            branches:
              only: master
    jobs:
      - commits