version: 2.1
jobs:
  commits:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - run:
          name: set up git
          command: |
            git config --global user.email "$USEREMAIL"
            git config --global user.name "$USERNAME"
      - run: 
          name: Make Commits
          command: | 
            git checkout master
            git commit --allow-empty -m "$CIRCLE_SHA1"
            git push -f

workflows:
  version: 2.1
  Make Commits:
    jobs:
      - commits:
          filters:
            branches:
              ignore: master
  Scheduled Commits:
    triggers:
      - schedule:
          cron: '0,10,20,30,40,50 1,2,3,4,5,6,9,15,18 * * *'
          filters:
            branches:
              only: master
    jobs:
      - commits