version: 2.1
jobs:
  commits:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - run:
          name: set up git
          command: |
            git config --global user.email "$USEREMAIL"
            git config --global user.name "$USERNAME"
      - run: 
          name: Make Commits
          command: | 
            git checkout master
            python run.py

workflows:
  version: 2.1
  Make Commits:
    jobs:
      - commits
  Scheduled Commits:
    triggers:
      - schedule:
          cron: '0 3,6,9,15,18 * * *'
          filters:
            branches:
              only: master
    jobs:
      - commits